# Generated by Django 4.2.20 on 2025-05-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emp_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
