# Generated by Django 5.2.4 on 2025-08-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_mealoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealoverride',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
