# Generated by Django 5.2.4 on 2025-08-20 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_mealoverride_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('source', models.CharField(choices=[('weekly', 'Weekly'), ('override', 'Override'), ('manual', 'Manual')], max_length=16)),
                ('item', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('present_count', models.IntegerField(default=0)),
                ('on_leave_count', models.IntegerField(default=0)),
                ('eaters_count', models.IntegerField(default=0)),
                ('eaters', models.JSONField(blank=True, default=list)),
                ('cutoff_time', models.TimeField(blank=True, default=None, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_cook_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
