# Generated by Django 5.2.4 on 2025-11-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0006_mealoptout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookrecord',
            name='opt_out_count',
            field=models.IntegerField(default=0),
        ),
    ]
