# Generated by Django 4.2.20 on 2025-07-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approval_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
