# Generated by Django 4.2.20 on 2025-07-04 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leave_approval_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
