# Generated by Django 5.2.4 on 2025-08-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_remove_leave_approval_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='half_day_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='informed_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
