# Generated by Django 5.2.4 on 2025-08-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leave_half_day_status_leave_informed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='half_day_status',
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('full_day', 'Full Day'), ('1st_half', 'First Half'), ('2nd_half', 'Second Half')], max_length=10),
        ),
    ]
