# Generated by Django 5.2.4 on 2025-08-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_remove_leave_date_remove_leave_half_day_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='start_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='date',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
