# Generated by Django 5.2.4 on 2025-12-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_remove_leave_end_date_remove_leave_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancel_pending', 'Cancel Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=256),
        ),
    ]
