# Generated by Django 5.2.4 on 2025-12-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_alter_leave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancel_pending', 'Cancel Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
