# Generated by Django 5.2.4 on 2025-10-10 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='member.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_member',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='members', through='member.MemberAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='memberassignment',
            index=models.Index(fields=['user'], name='user_member_user_id_355ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='memberassignment',
            index=models.Index(fields=['member'], name='user_member_member__e11204_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memberassignment',
            unique_together={('user', 'member')},
        ),
    ]
