# Generated by Django 5.2.4 on 2025-10-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_memberassignment_member_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
