# Generated by Django 5.2.4 on 2026-01-07 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='memberassignment',
            name='sign_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_in_assignments', to='member.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='members', through='member.MemberAssignment', through_fields=('member', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='memberassignment',
            unique_together={('user', 'member', 'sign_in')},
        ),
        migrations.AddIndex(
            model_name='memberassignment',
            index=models.Index(fields=['sign_in'], name='user_member_sign_in_928e31_idx'),
        ),
    ]
