# Generated by Django 5.2.4 on 2026-01-07 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_memberassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberassignment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='member.member'),
        ),
    ]
