# Generated by Django 5.2.4 on 2026-01-07 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_memberassignment_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='memberassignment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='member.member'),
        ),
        migrations.AlterField(
            model_name='memberassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
